favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 0.4752954
  lightness: 0.9940923
  brandColors:
    - '#003D62'
    - '#FFFFFF'
    - '#DAE2E7'
    - '#8BA8B8'
    - '#2B5775'
  rhythmicContrast: 0
typography_spectrum: 0.2690655
layout_spectrum: 0.2604726
cta:
  bucket: null
  version: null
  domain: null
name: Stephen Blake Photographic
